# Numpy Review Problem Set

In [1]:
import numpy as np

#### Create an all zero numpy array of size 1000

In [2]:
# write code here

#### Create a numpy array from all digits between [0,1000) that are divisible by five

In [3]:
# write code here

#### Assign a 1 to every element divisible by 5 in the all zero array

In [4]:
# write code here

#### Below is the grades for 6 students, convert to a numpy array

In [5]:
grades = [90, 94, 88, 80, 78, 85]
# write code here

#### Scale every grade below 90 up by 2 points

In [6]:
# write code here

#### Create a 10 by 10 matrix with 1 on the border 0 within the border

In [12]:
# write code here
# solution: delete !!!
# Z = np.ones((10,10))
# Z[1:-1,1:-1] = 0
# Z

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

## Challenge Problems

#### Create an 10 by 10 checkerboard matrix in three lines of code.
Below is an example of a 3 by 3 checkerboard matrix

In [ ]:
# [0 1 0]
# [1 0 1]
# [0 1 0]

In [ ]:
# write code here
#solution below delete !!!!
# Z = np.zeros((8,8),dtype=int)
# Z[1::2,::2] = 1
# Z[::2,1::2] = 1
# print(Z)

#### Assume that you have an MxM array, a, and a number, n (where n < M). Using array attributes and slicing, print out the nxn subarray at the center of a (example below for n=3, M=5-- you may assume that n is odd and that a has an odd number of rows and columns) 

In [9]:
#
# 0 0 0 0 0
# 0 X X X 0      X X X
# 0 X X X 0 ---> X X X
# 0 X X X 0      X X X
# 0 0 0 0 0

In [ ]:
# write code here

#### Compute the Euclidean distance between the two arrays provided below

In [ ]:
The Euclidean distance (also called the L2 distance) between X and Y is defined as:
dist((x, y), (a, b)) = √[(x - a)² + (y - b)²]

In [ ]:
x = np.array([1., 0., 3.5])
y = np.array([2.3, -1., 0.])
# write code here